CREATE TABLE public.player (
    id bigint generated by default as identity,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

CREATE TABLE public.sallys (
                               id bigint generated by default as identity,
                               type VARCHAR(100) NOT NULL
);

CREATE TABLE public.scores (
                               id bigint generated by default as identity,
                               player_id INT NOT NULL,
                               sally_type_id INT NOT NULL,
                               weight VARCHAR(15),
                               duration VARCHAR(25) NOT NULL,
                               score_date date NOT NULL,
                               notes VARCHAR(255),
                               primary key (id)
);

ALTER TABLE public.scores
    ADD FOREIGN KEY (sally_type_id)
        REFERENCES sallys(id);

ALTER TABLE public.scores
    ADD FOREIGN KEY (player_id)
        REFERENCES player(id);